import {useEffect,useMemo,useRef,useState} from 'react';
import {useVirtualizer} from '@tanstack/react-virtual';
import {Check,Copy,Search,X} from 'lucide-react';
import {api,duration,type Artifact,type Job} from '../types';

type Props={job:Job|null;kind:'srt'|'txt';onKind:(k:'srt'|'txt')=>void;onClose:()=>void};
export default function ResultPanel({job,kind,onKind,onClose}:Props){const [artifact,setArtifact]=useState<Artifact|null>(null);const [query,setQuery]=useState('');const [error,setError]=useState('');const [copied,setCopied]=useState(false);const scrollRef=useRef<HTMLDivElement>(null);
 useEffect(()=>{setArtifact(null);setError('');setQuery('');if(!job||!job.available?.includes(kind))return;void api<Artifact>(`/jobs/${job.id}/artifacts/${kind}`).then(setArtifact).catch(e=>setError(e instanceof Error?e.message:String(e)))},[job,kind]);
 useEffect(()=>{if(!job)return;const onKey=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose()};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[job,onClose]);
 const lines=useMemo(()=>artifact?.segments?.filter(s=>!query||s.text.toLocaleLowerCase().includes(query.toLocaleLowerCase()))||[],[artifact,query]);
 const virtualizer=useVirtualizer({count:lines.length,getScrollElement:()=>scrollRef.current,estimateSize:()=>72,overscan:8});
 if(!job)return null;return <aside className="result-panel" aria-label="转写结果"><div className="result-head"><div><h2>{job.media.name}</h2><p title={job.media.path}>{job.media.path}</p></div><button className="icon-btn" onClick={onClose} aria-label="关闭结果"><X/></button></div><div className="result-tabs"><button className={kind==='txt'?'active':''} disabled={!job.available?.includes('txt')} onClick={()=>onKind('txt')}>文字稿</button><button className={kind==='srt'?'active':''} disabled={!job.available?.includes('srt')} onClick={()=>onKind('srt')}>字幕</button></div><div className="result-tools"><label className="search-box"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索结果"/></label><button className="secondary" disabled={!artifact} onClick={()=>{if(!artifact)return;void navigator.clipboard.writeText(artifact.text).then(()=>{setCopied(true);setTimeout(()=>setCopied(false),1200)})}}>{copied?<Check size={16}/>:<Copy size={16}/>} {copied?'已复制':'复制全文'}</button></div>{error&&<div className="error">{error}</div>}<div className="result-meta">结果来源：{artifact?.origin||'—'} · 语言：{job.language||'自动'} · 设备：{job.device||'—'}</div><div className="reader" ref={scrollRef}>{kind==='txt'?<pre>{artifact?.text||'正在读取…'}</pre>:!artifact?<pre>正在读取…</pre>:lines.length?<div style={{height:virtualizer.getTotalSize(),position:'relative'}}>{virtualizer.getVirtualItems().map(v=>{const s=lines[v.index];return <div className="timeline-row" key={`${s.start}-${v.index}`} style={{position:'absolute',top:0,left:0,width:'100%',minHeight:v.size,transform:`translateY(${v.start}px)`}}><span>{duration(s.start)} → {duration(s.end)}</span><p>{s.text}</p></div>})}</div>:<div className="empty big">没有匹配的字幕</div>}</div></aside>}
